### ISSUE TITLE
Dynacam does not work with Composer

### ISSUE THREAD

**Issue by mgodf7** [Zetosoft/dynacam#2]
Is it possible to use Dynacam with Composer?

For instance, when I call the setup functions in the `dynacam-demo` project from Composer events, I just get a blank screen.

Thanks!

```lua
--^^^ Rest of dynacam-demo main.lua ^^^
---------------------------------------

local composer = require( "composer" )

local scene = composer.newScene()

function scene:create( event )
end

function scene:show( event )
    initialize()
    createWorld()
    createSliders()
    startGame()
end

function scene:hide( event )
end

function scene:destroy( event )
end

-- -----------------------------------------------------------------------------------
-- Scene event function listeners
-- -----------------------------------------------------------------------------------
scene:addEventListener( "create", scene )
scene:addEventListener( "show", scene )
scene:addEventListener( "hide", scene )
scene:addEventListener( "destroy", scene )

return scene
```

**Comment by CetoBasilius** [comment]
Yes! of course!

In the example above, you should have this in main.lua: (If you placed the scene file at scenes/demo.lua)

```
local composer = require("composer")
composer.gotoScene("scenes.demo")
```

And also in the composer scene, the `scene:show` listener gets called twice, you should either put it on the `create` or put the `event.phase` if, like so:

```
function scene:show(event)
	if event.phase == "did" then -- or "will"
		initialize()
		createWorld()
		createSliders()
		startGame()
	end
end
```

It worked for me, please be aware that this scene will crash if `gotoScene` is called twice for it, you should stop dynacam in the `hide` event and not create objects and camera twice. This is mostly composer related stuff, so practice a bit with composer scenes and object creation/deletion
